[package]
name = "runner-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version= "1.1.6", features = ["behavior-version-latest"] }
aws-sdk-sqs = "1.14.0"
tokio = { version = "1", features = ["full"] }
dotenvy ={ version = "0.15.7"}
